### ISSUE TITLE
Prompt ssh-key if no ssh key path given

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena-plugin-upcloud#22]
Plugin should prompt list of uploaded keys from UC if no ssh key path is given. If path is given then plugin should upload a public key to UC and use that for provisioning.

**Comment by kke** [comment]
There's no documented API for listing or uploading SSH keys.

The SSH keys that you enter in the upcloud dashboard can only be used when manually creating a new server through the web page.

When deploying using the API, the SSH public keys are listed in an array as-is, `ssh_keys: ['ssh-rsa xxx yy', '...']`.

The solution can only try to read it from a file or if that fails, ask for a copy-paste.
